[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

# Skip all library internals
skip = ["lib/openzeppelin-contracts/certora/**", "lib/openzeppelin-contracts/test/**", "lib/**/test/**"]
