[profile.default]
src = "."
out = "out"
libs = ["../../node_modules", "lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

solc_version = "0.8.23"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"
